import "package:flutter/widgets.dart";
import "package:flutter_first_app/localization/generated/app_localizations.dart" show AppLocalizations;

/// Groups the `common*` keys from the .arb files under a single namespace.
/// Strings that repeat across many screens (buttons, generic actions) live here.
class CommonStrings {
  const CommonStrings(this._t);
  final AppLocalizations _t;

  String get ok => _t.commonOk;
  String get cancel => _t.commonCancel;
  String get confirm => _t.commonConfirm;
  String get continueLabel => _t.commonContinue;
  String get close => _t.commonClose;
  String get save => _t.commonSave;
  String get typeHere => _t.commonTypeHere;
}

/// Groups the `pageHome*` keys — only used inside the Home page.
class PageHomeStrings {
  const PageHomeStrings(this._t);
  final AppLocalizations _t;

  String get title => _t.pageHomeTitle;
  String get welcome => _t.pageHomeWelcome;
  String get buttonClick => _t.pageHomeButtonClick;
}

/// Groups the `pageSettings*` keys — only used inside the Settings page.
class PageSettingsStrings {
  const PageSettingsStrings(this._t);
  final AppLocalizations _t;

  String get title => _t.pageSettingsTitle;
  String get languageLabel => _t.pageSettingsLanguageLabel;
  String get themeLabel => _t.pageSettingsThemeLabel;
}

/// Ergonomic, namespaced entry point over the flat `AppLocalizations` class
/// generated by `flutter gen-l10n`.
///
/// `AppLocalizations` only exposes a flat list of getters/methods (one per
/// .arb key) — it has no concept of nested objects. Namespacing here (`common`,
/// `pageHome`, ...) is purely a Dart-side convenience: keys in the .arb files
/// still use a flat `commonX` / `pageHomeX` naming convention, and this class
/// just regroups them for a nicer call-site syntax.
///
/// Add a getter here for every new namespace, matching the .arb key prefix.
class L10n {
  const L10n(this._t);
  final AppLocalizations _t;

  factory L10n.of(BuildContext context) => L10n(AppLocalizations.of(context));

  /// Keys without a namespace prefix (e.g. `hello`, `welcomeWithName`) stay
  /// reachable directly, for quick one-off strings that don't belong to any
  /// group yet.
  AppLocalizations get raw => _t;

  CommonStrings get common => CommonStrings(_t);
  PageHomeStrings get pageHome => PageHomeStrings(_t);
  PageSettingsStrings get pageSettings => PageSettingsStrings(_t);
}
