name: flutter_first_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  uuid: 4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/easywatchlist-logo-black.png
    - assets/images/easywatchlist-logo-white.png

fonts:
  - family: Urbanist
    fonts:
      # Thin
      - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
        weight: 100
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-ThinItalic.ttf
        weight: 100
        style: italic
      # ExtraLight
      - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
        weight: 200
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-ExtraLightItalic.ttf
        weight: 200
        style: italic
      # Light
      - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
        weight: 300
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-LightItalic.ttf
        weight: 300
        style: italic
      # Regular
      - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        weight: 400
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-Italic.ttf
        weight: 400
        style: italic
      # Medium
      - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
        weight: 500
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-MediumItalic.ttf
        weight: 500
        style: italic
      # SemiBold
      - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
        weight: 600
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-SemiBoldItalic.ttf
        weight: 600
        style: italic
      # Bold
      - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        weight: 700
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.ttf
        weight: 700
        style: italic
      # ExtraBold
      - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
        weight: 800
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      # Black
      - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
        weight: 900
        style: normal
      - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
        weight: 900
        style: italic

  - family: DynaPuff
    fonts:
      # Regular
      - asset: assets/fonts/DynaPuff/DynaPuff-Regular.ttf
        weight: 400
        style: normal
      # Medium
      - asset: assets/fonts/DynaPuff/DynaPuff-Medium.ttf
        weight: 500
        style: normal
      # SemiBold
      - asset: assets/fonts/DynaPuff/DynaPuff-SemiBold.ttf
        weight: 600
        style: normal
      # Bold
      - asset: assets/fonts/DynaPuff/DynaPuff-Bold.ttf
        weight: 700
        style: normal